// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vshn/cdays-webui-poc/models"
)

// CreateManagedNamespaceReader is a Reader for the CreateManagedNamespace structure.
type CreateManagedNamespaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateManagedNamespaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateManagedNamespaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateManagedNamespaceOK creates a CreateManagedNamespaceOK with default headers values
func NewCreateManagedNamespaceOK() *CreateManagedNamespaceOK {
	return &CreateManagedNamespaceOK{}
}

/*CreateManagedNamespaceOK handles this case with default header values.

create a new managed namespace
*/
type CreateManagedNamespaceOK struct {
	Payload *models.Namespace
}

func (o *CreateManagedNamespaceOK) Error() string {
	return fmt.Sprintf("[PUT /{clustername}/namespace/{customer}][%d] createManagedNamespaceOK  %+v", 200, o.Payload)
}

func (o *CreateManagedNamespaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Namespace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
