// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vshn/cdays-webui-poc/models"
)

// GetManagedNamespaceReader is a Reader for the GetManagedNamespace structure.
type GetManagedNamespaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetManagedNamespaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetManagedNamespaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetManagedNamespaceOK creates a GetManagedNamespaceOK with default headers values
func NewGetManagedNamespaceOK() *GetManagedNamespaceOK {
	return &GetManagedNamespaceOK{}
}

/*GetManagedNamespaceOK handles this case with default header values.

returns a single namespace
*/
type GetManagedNamespaceOK struct {
	Payload *models.Namespace
}

func (o *GetManagedNamespaceOK) Error() string {
	return fmt.Sprintf("[GET /namespace/{customer}/{name}][%d] getManagedNamespaceOK  %+v", 200, o.Payload)
}

func (o *GetManagedNamespaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Namespace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
