// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vshn/cdays-webui-poc/models"
)

// UpdateManagedNamespaceReader is a Reader for the UpdateManagedNamespace structure.
type UpdateManagedNamespaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateManagedNamespaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateManagedNamespaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateManagedNamespaceOK creates a UpdateManagedNamespaceOK with default headers values
func NewUpdateManagedNamespaceOK() *UpdateManagedNamespaceOK {
	return &UpdateManagedNamespaceOK{}
}

/*UpdateManagedNamespaceOK handles this case with default header values.

deletes a single namespace
*/
type UpdateManagedNamespaceOK struct {
	Payload *models.Namespace
}

func (o *UpdateManagedNamespaceOK) Error() string {
	return fmt.Sprintf("[POST /{clustername}/namespace/{customer}/{name}][%d] updateManagedNamespaceOK  %+v", 200, o.Payload)
}

func (o *UpdateManagedNamespaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Namespace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
