// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vshn/cdays-webui-poc/models"
)

// NewUpdateManagedNamespaceParams creates a new UpdateManagedNamespaceParams object
// with the default values initialized.
func NewUpdateManagedNamespaceParams() *UpdateManagedNamespaceParams {
	var ()
	return &UpdateManagedNamespaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateManagedNamespaceParamsWithTimeout creates a new UpdateManagedNamespaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateManagedNamespaceParamsWithTimeout(timeout time.Duration) *UpdateManagedNamespaceParams {
	var ()
	return &UpdateManagedNamespaceParams{

		timeout: timeout,
	}
}

// NewUpdateManagedNamespaceParamsWithContext creates a new UpdateManagedNamespaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateManagedNamespaceParamsWithContext(ctx context.Context) *UpdateManagedNamespaceParams {
	var ()
	return &UpdateManagedNamespaceParams{

		Context: ctx,
	}
}

// NewUpdateManagedNamespaceParamsWithHTTPClient creates a new UpdateManagedNamespaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateManagedNamespaceParamsWithHTTPClient(client *http.Client) *UpdateManagedNamespaceParams {
	var ()
	return &UpdateManagedNamespaceParams{
		HTTPClient: client,
	}
}

/*UpdateManagedNamespaceParams contains all the parameters to send to the API endpoint
for the update managed namespace operation typically these are written to a http.Request
*/
type UpdateManagedNamespaceParams struct {

	/*Body*/
	Body *models.Namespace
	/*Customer*/
	Customer string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update managed namespace params
func (o *UpdateManagedNamespaceParams) WithTimeout(timeout time.Duration) *UpdateManagedNamespaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update managed namespace params
func (o *UpdateManagedNamespaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update managed namespace params
func (o *UpdateManagedNamespaceParams) WithContext(ctx context.Context) *UpdateManagedNamespaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update managed namespace params
func (o *UpdateManagedNamespaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update managed namespace params
func (o *UpdateManagedNamespaceParams) WithHTTPClient(client *http.Client) *UpdateManagedNamespaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update managed namespace params
func (o *UpdateManagedNamespaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update managed namespace params
func (o *UpdateManagedNamespaceParams) WithBody(body *models.Namespace) *UpdateManagedNamespaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update managed namespace params
func (o *UpdateManagedNamespaceParams) SetBody(body *models.Namespace) {
	o.Body = body
}

// WithCustomer adds the customer to the update managed namespace params
func (o *UpdateManagedNamespaceParams) WithCustomer(customer string) *UpdateManagedNamespaceParams {
	o.SetCustomer(customer)
	return o
}

// SetCustomer adds the customer to the update managed namespace params
func (o *UpdateManagedNamespaceParams) SetCustomer(customer string) {
	o.Customer = customer
}

// WithName adds the name to the update managed namespace params
func (o *UpdateManagedNamespaceParams) WithName(name string) *UpdateManagedNamespaceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update managed namespace params
func (o *UpdateManagedNamespaceParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateManagedNamespaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param customer
	if err := r.SetPathParam("customer", o.Customer); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
