// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllClustersParams creates a new GetAllClustersParams object
// with the default values initialized.
func NewGetAllClustersParams() *GetAllClustersParams {

	return &GetAllClustersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllClustersParamsWithTimeout creates a new GetAllClustersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllClustersParamsWithTimeout(timeout time.Duration) *GetAllClustersParams {

	return &GetAllClustersParams{

		timeout: timeout,
	}
}

// NewGetAllClustersParamsWithContext creates a new GetAllClustersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllClustersParamsWithContext(ctx context.Context) *GetAllClustersParams {

	return &GetAllClustersParams{

		Context: ctx,
	}
}

// NewGetAllClustersParamsWithHTTPClient creates a new GetAllClustersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllClustersParamsWithHTTPClient(client *http.Client) *GetAllClustersParams {

	return &GetAllClustersParams{
		HTTPClient: client,
	}
}

/*GetAllClustersParams contains all the parameters to send to the API endpoint
for the get all clusters operation typically these are written to a http.Request
*/
type GetAllClustersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all clusters params
func (o *GetAllClustersParams) WithTimeout(timeout time.Duration) *GetAllClustersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all clusters params
func (o *GetAllClustersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all clusters params
func (o *GetAllClustersParams) WithContext(ctx context.Context) *GetAllClustersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all clusters params
func (o *GetAllClustersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all clusters params
func (o *GetAllClustersParams) WithHTTPClient(client *http.Client) *GetAllClustersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all clusters params
func (o *GetAllClustersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllClustersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
